services:
  echo:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - 5059:5059
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    network_mode: host

  shout:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      - ECHO_SERVICE_URL=http://echo:5059/e
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    network_mode: host
